
on:
  push:
    branches:
      - main  # Adjust this to your default branch
#   schedule:
#     - cron: '0 0 * * *'  # Adjust this to your schedule if needed

jobs:
  CI_Pipeline:
    runs-on: self-hosted

    env:
      CONDA: "/home/ubuntu/miniconda3/"
      CONDA_ENV_NAME: "hadaca3framework_env"
      # REPO_DIR: "/home/runner/work/your-repo/your-repo"  # Adjust this to your repo path
      SNK_CORES: "4"
      MEM_MB: "16000"


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          auto-activate-base: false
      - name: Create Conda environment
        run: |
          conda create -y -n ${{ env.CONDA_ENV_NAME }}

      - name: Activate Conda environment
        run: |
          conda activate ${{ env.CONDA_ENV_NAME }}

      # - name: Fetch all branches
      #   run: |
      #     git fetch --all
      #     git reset --hard ${{ github.sha }}

      - name: Execute commands from README
        run: |
          awk '/```/{if (!first_block_found) {f=!f; first_block_found=1; next} else {exit} } f' README.md | while read -r line; do
            [[ "\$line" =~ ^# ]] && continue
            [ -z "\$line" ] || [[ "\$line" =~ conda\ create ]] && continue
            echo "Executing: \$line"
            $line
          done


# name: 



#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Miniconda
#         uses: conda-incubator/setup-miniconda@v2
#         with:
#           activate-environment: ${{ env.CONDA_ENV_NAME }}
#           auto-activate-base: false

#       - name: Create Conda environment
#         run: |
#           conda create -y -n ${{ env.CONDA_ENV_NAME }}

#       - name: Activate Conda environment
#         run: |
#           conda activate ${{ env.CONDA_ENV_NAME }}

#       - name: Fetch all branches
#         run: |
#           git fetch --all
#           git reset --hard ${{ github.sha }}

#       - name: Execute commands from README
#         run: |
#           awk '/```/{if (!first_block_found) {f=!f; first_block_found=1; next} else {exit} } f' README.md | while read -r line; do
#             [[ "\$line" =~ ^# ]] && continue
#             [ -z "\$line" ] || [[ "\$line" =~ conda\ create ]] && continue
#             echo "Executing: \$line"
#             $line
#           done

#       - name: Run Snakemake
#         run: |
#           snakemake --cores ${{ env.SNK_CORES }} -s 00_run_pipeline.smk -p clean
#           snakemake --cores ${{ env.SNK_CORES }} -s 00_run_pipeline.smk -p --resources mem_mb=${{ env.MEM_MB }} --max-jobs-per-second 1

#       - name: Prepare artifacts
#         run: |
#           mkdir -p public
#           cp 05_metaanalysis.html public/index.html

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: public
#           path: public/
